################################################################
# API and dashboard configuration
################################################################
loglevel="ERROR"

defaultEntryPoints = ["http", "ws"]

[entryPoints]
    [entryPoints.http]
        address = ":80"
[api]
    entrypoint="dashboard"
 
################################################################
# Docker configuration backend
################################################################
[docker]
    domain = "docker.local"
    watch = true
    network = "frontnet"